#!/bin/bash
#SBATCH --job-name=Nek5000
#SBATCH --nodes=10
#SBATCH --ntasks-per-node=2
#SBATCH --mem-per-cpu=10gb
#SBATCH --time=24:00:00
#SBATCH --account=ebm5351_b_gpu
#SBATCH --partition=sla-prio


module load intel/2023.0 mpi/latest

module list

cd $SLURM_SUBMIT_DIR

cat $SLURM_JOB_NODELIST | uniq

echo "casename" >  SESSION.NAME
echo `pwd`'/' >>  SESSION.NAME
rm -f logfile
rm -f ioinfo
srun ./nek5000 > logfile
